In [97]:
with open("the-verdict.txt",'r',encoding='utf-8') as f:
    raw_text = f.read()

In [2]:
import re

In [40]:
text = "Hello, world. This, is-- a test.  ?.  test"

result = re.split(r'([,.:;?_!"()\']|--|\s)',text)

In [41]:
[item for item in result if item.strip()]

['Hello',
 ',',
 'world',
 '.',
 'This',
 ',',
 'is',
 '--',
 'a',
 'test',
 '.',
 '?',
 '.',
 'test']

In [42]:

result

['Hello',
 ',',
 '',
 ' ',
 'world',
 '.',
 '',
 ' ',
 'This',
 ',',
 '',
 ' ',
 'is',
 '--',
 '',
 ' ',
 'a',
 ' ',
 'test',
 '.',
 '',
 ' ',
 '',
 ' ',
 '',
 '?',
 '',
 '.',
 '',
 ' ',
 '',
 ' ',
 'test']

In [43]:
preprocessed = re.split(r'([,.:;?_!"()\']|--|\s)', raw_text)
preprocessed = [item.strip() for item in preprocessed if item.strip()]
print(preprocessed[:30])

['I', 'HAD', 'always', 'thought', 'Jack', 'Gisburn', 'rather', 'a', 'cheap', 'genius', '--', 'though', 'a', 'good', 'fellow', 'enough', '--', 'so', 'it', 'was', 'no', 'great', 'surprise', 'to', 'me', 'to', 'hear', 'that', ',', 'in']


In [44]:
all_words = sorted(set(preprocessed))
vocab_size = len(all_words)

In [47]:
vocab = {item:integer for integer,item in enumerate(all_words)}

['!',
 '"',
 "'",
 '(',
 ')',
 ',',
 '--',
 '.',
 ':',
 ';',
 '?',
 'A',
 'Ah',
 'Among',
 'And',
 'Are',
 'Arrt',
 'As',
 'At',
 'Be',
 'Begin',
 'Burlington',
 'But',
 'By',
 'Carlo',
 'Chicago',
 'Claude',
 'Come',
 'Croft',
 'Destroyed',
 'Devonshire',
 'Don',
 'Dubarry',
 'Emperors',
 'Florence',
 'For',
 'Gallery',
 'Gideon',
 'Gisburn',
 'Gisburns',
 'Grafton',
 'Greek',
 'Grindle',
 'Grindles',
 'HAD',
 'Had',
 'Hang',
 'Has',
 'He',
 'Her',
 'Hermia',
 'His',
 'How',
 'I',
 'If',
 'In',
 'It',
 'Jack',
 'Jove',
 'Just',
 'Lord',
 'Made',
 'Miss',
 'Money',
 'Monte',
 'Moon-dancers',
 'Mr',
 'Mrs',
 'My',
 'Never',
 'No',
 'Now',
 'Nutley',
 'Of',
 'Oh',
 'On',
 'Once',
 'Only',
 'Or',
 'Perhaps',
 'Poor',
 'Professional',
 'Renaissance',
 'Rickham',
 'Riviera',
 'Rome',
 'Russian',
 'Sevres',
 'She',
 'Stroud',
 'Strouds',
 'Suddenly',
 'That',
 'The',
 'Then',
 'There',
 'They',
 'This',
 'Those',
 'Though',
 'Thwing',
 'Thwings',
 'To',
 'Usually',
 'Venetian',
 'Victor',
 '

In [64]:
class SimpleTokenizerV1:
    def __init__(self, vocab):
        self.str_to_int = vocab
        self.int_to_str = {i:s for s,i in vocab.items()}
        
    def encode(self, text):
        preprocessed = re.split(r'([,.:;?_!"()\']|--|\s)', text)
        
        preprocessed = [
            item.strip() for item in preprocessed if item.strip()
        ]
        ids = [self.str_to_int[s] if s in self.str_to_int else self.str_to_int['<|unk|>'] for s in preprocessed ]
        return ids
    
    def decode(self, ids):
        text = " ".join([self.int_to_str[i] for i in ids])
        text = re.sub(r'\s+([,.?!"()\'])', r'\1', text)

        return text

In [55]:
tokenizer = SimpleTokenizerV1(vocab)

In [58]:
encoded = tokenizer.encode("HEllo i am testing this")


In [60]:
tokenizer = SimpleTokenizerV1(vocab)

text = """"It's the last he painted, you know," 
           Mrs. Gisburn said with pardonable pride."""
ids = tokenizer.encode(text)
print(ids)

[1, 56, 2, 850, 988, 602, 533, 746, 5, 1126, 596, 5, 1, 67, 7, 38, 851, 1108, 754, 793, 7]


In [62]:
print(tokenizer.decode(ids))

" It' s the last he painted, you know," Mrs. Gisburn said with pardonable pride.


In [65]:
all_tokens = sorted(list(set(preprocessed)))
all_tokens.extend(["<|endoftext|>", "<|unk|>"])

vocab = {token:integer for integer,token in enumerate(all_tokens)}

In [70]:
tokenizer = SimpleTokenizerV1(vocab)

text1 = "Hello, do you like tea?"
text2 = "In the sublit terraces of the palace"

text = "<|endoftext|>".join((text1,text2))

In [71]:
tokenizer.decode(tokenizer.encode(text))

'<|unk|>, do you like tea? <|unk|> the <|unk|> terraces of the <|unk|>'

In [72]:
#Byte pair Encoding

In [85]:
import tiktoken

tokenizer = tiktoken.get_encoding("gpt2")

text = (
    "Hello, do you like tea? <|endoftext|> In the sunlit terraces"
     "of someunknownPlace."
)


integers = tokenizer.encode(text, allowed_special={"<|endoftext|>"})

In [86]:
tokenizer.decode(integers)

'Hello, do you like tea? <|endoftext|> In the sunlit terracesof someunknownPlace.'

In [92]:
encodings = {
    "gpt2":tiktoken.get_encoding("gpt2"),
    "gpt3":tiktoken.get_encoding("p50k_base"),
    "gpt4":tiktoken.get_encoding("cl100k_base"),
    
}

vocab_size = {model: encoding.n_vocab for model,encoding in encodings.items()}

for model, size in vocab_size.items():
    print(f"The vocab size for {model} is {size}")

The vocab size for gpt2 is 50257
The vocab size for gpt3 is 50281
The vocab size for gpt4 is 100277


In [91]:
vocab_size

{'gpt2': 50257, 'gpt3': 50281, 'gpt4': 100277}

In [104]:
import torch
from torch.utils.data import Dataset, DataLoader

class GPTDatasetV1(Dataset):
    def __init__(self, txt, tokenizer, max_length, stride):
        self.input_ids = []
        self.target_ids = []
        
        token_ids = tokenizer.encode(txt, allowed_special={"<|endoftext|>"})
        
        for i in range(0,len(token_ids)-max_length, stride):
            input_chunk = token_ids[i:i+max_length]
            output_chunk = token_ids[i+1:i+1+max_length]
            self.input_ids.append(torch.tensor(input_chunk))
            self.target_ids.append(torch.tensor(output_chunk))
            
    def __len__(self):
        return len(self.input_ids)
    
    def __getitem__(self, idx):
        return self.input_ids[idx],self.target_ids[idx]

In [105]:
dataset = GPTDatasetV1(raw_text,tokenizer,4,2)

In [106]:
dataloader = DataLoader(dataset,batch_size=8,shuffle=False)

In [116]:
def create_dataloader_v1(txt,batch_size=4,max_length=256,stride=128,shuffle=True,drop_last=True):
    tokenizer = tiktoken.get_encoding("gpt2")
    dataset = GPTDatasetV1(txt,tokenizer,max_length,stride)
    
    dataloader = DataLoader(
        dataset,
        batch_size=batch_size,
        shuffle=shuffle,
        drop_last=drop_last
    )
    
    return dataloader

In [117]:
dataloader = create_dataloader_v1(
    raw_text, batch_size=1, max_length=4, stride=1, shuffle=False
)

data_iter = iter(dataloader)
first_batch = next(data_iter)
print(first_batch)

[tensor([[  40,  367, 2885, 1464]]), tensor([[ 367, 2885, 1464, 1807]])]


In [118]:
dataloader = create_dataloader_v1(raw_text, batch_size=8, max_length=4, stride=4, shuffle=False)

data_iter = iter(dataloader)
inputs, targets = next(data_iter)
print("Inputs:\n", inputs)
print("\nTargets:\n", targets)

Inputs:
 tensor([[   40,   367,  2885,  1464],
        [ 1807,  3619,   402,   271],
        [10899,  2138,   257,  7026],
        [15632,   438,  2016,   257],
        [  922,  5891,  1576,   438],
        [  568,   340,   373,   645],
        [ 1049,  5975,   284,   502],
        [  284,  3285,   326,    11]])

Targets:
 tensor([[  367,  2885,  1464,  1807],
        [ 3619,   402,   271, 10899],
        [ 2138,   257,  7026, 15632],
        [  438,  2016,   257,   922],
        [ 5891,  1576,   438,   568],
        [  340,   373,   645,  1049],
        [ 5975,   284,   502,   284],
        [ 3285,   326,    11,   287]])


In [119]:
input_ids = torch.tensor([2,3,5,1])

In [120]:
vocab_size=6
output_dim = 3

In [121]:
#Embedding
from torch import nn

embedding = nn.Embedding(vocab_size,output_dim)

In [127]:
embedding(input_ids)

tensor([[-1.5971, -1.3160, -0.6500],
        [ 0.0946, -1.0633,  0.3112],
        [ 0.4493,  0.0504,  0.3773],
        [-1.4798,  1.3728, -0.2862]], grad_fn=<EmbeddingBackward0>)

In [128]:
#Positional Embedding

In [143]:
vocab_size = 50257
output_dim = 256

token_embedding_layer = nn.Embedding(vocab_size,output_dim)

In [132]:
max_length = 4
dataloader = create_dataloader_v1(
    raw_text, batch_size=8, max_length=max_length,
    stride=max_length, shuffle=False
)
data_iter = iter(dataloader)
inputs, targets = next(data_iter)

In [137]:
token_embeddings = token_embedding_layer(inputs)

In [153]:

token_embedding_layer(torch.tensor([0]))

tensor([[ 1.7505, -1.6099, -0.7765,  0.2307, -0.1435, -0.5554, -1.0015, -0.5450,
          0.6731,  0.6811, -0.0442, -1.4914, -0.8475,  1.4379,  1.2102, -1.0405,
         -0.8321, -0.9186, -0.8992,  0.6360, -0.2776,  0.3994,  0.9825, -1.2509,
         -0.2250, -0.9712,  1.2332,  0.5613, -1.1850, -2.5315, -0.4711, -0.4844,
         -1.8478,  0.2917,  0.5772, -2.1218, -0.9251,  1.5011,  1.5563,  0.2824,
         -1.2502, -1.2802,  0.5946,  0.8912, -0.2161, -0.9418, -0.8641,  1.5533,
          0.1477, -0.3288, -0.5943, -1.1993,  1.3745,  0.4937,  0.0174, -1.0196,
         -0.2864,  0.2731,  1.2032, -0.7857, -0.0281, -1.7425, -1.5720, -1.2515,
         -0.8142, -0.5544, -0.4541, -0.6415, -0.2308, -0.5757, -1.0518,  0.0204,
          0.1586, -0.8134,  1.7683, -0.4985,  1.4663, -0.3481, -1.1835, -0.0375,
         -1.1134, -0.4078, -0.2613, -0.9268,  0.0762, -1.1953, -0.0822, -0.0502,
         -0.4343, -0.0745,  0.4503,  0.3620,  1.5415, -0.2774,  0.2013,  0.9301,
          0.7097, -0.1409,  

In [155]:
max_length =4

pos_embedding_layer = nn.Embedding(max_length,output_dim)

In [157]:
pos_embedding_layer.weight

Parameter containing:
tensor([[-1.0292,  0.5787,  1.4943,  ..., -0.0344,  0.5735, -0.1048],
        [ 0.8385,  0.5713, -1.9317,  ..., -1.1964, -0.6756, -1.4118],
        [ 0.8971,  0.6961,  0.6476,  ...,  2.4527,  0.7715, -0.4936],
        [ 1.1229, -0.6806, -0.5861,  ..., -0.8031, -0.1561, -1.6713]],
       requires_grad=True)